name: modul_cam_qr_1441
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  camera: ^0.10.5+2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  mobile_scanner: ^3.2.0
  path: any
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
